import { diagnostic, didYouMean, type Parsed } from '../diagnostics.ts';
export const GM_PROGRAMS: readonly string[] = [
  "acoustic_grand_piano",
  "bright_acoustic_piano",
  "electric_grand_piano",
  "honky_tonk_piano",
  "electric_piano_1",
  "electric_piano_2",
  "harpsichord",
  "clavinet",
  "celesta",
  "glockenspiel",
  "music_box",
  "vibraphone",
  "marimba",
  "xylophone",
  "tubular_bells",
  "dulcimer",
  "drawbar_organ",
  "percussive_organ",
  "rock_organ",
  "church_organ",
  "reed_organ",
  "accordion",
  "harmonica",
  "tango_accordion",
  "acoustic_guitar_nylon",
  "acoustic_guitar_steel",
  "electric_guitar_jazz",
  "electric_guitar_clean",
  "electric_guitar_muted",
  "overdriven_guitar",
  "distortion_guitar",
  "guitar_harmonics",
  "acoustic_bass",
  "electric_bass_finger",
  "electric_bass_pick",
  "fretless_bass",
  "slap_bass_1",
  "slap_bass_2",
  "synth_bass_1",
  "synth_bass_2",
  "violin",
  "viola",
  "cello",
  "contrabass",
  "tremolo_strings",
  "pizzicato_strings",
  "orchestral_harp",
  "timpani",
  "string_ensemble_1",
  "string_ensemble_2",
  "synth_strings_1",
  "synth_strings_2",
  "choir_aahs",
  "voice_oohs",
  "synth_voice",
  "orchestra_hit",
  "trumpet",
  "trombone",
  "tuba",
  "muted_trumpet",
  "french_horn",
  "brass_section",
  "synth_brass_1",
  "synth_brass_2",
  "soprano_sax",
  "alto_sax",
  "tenor_sax",
  "baritone_sax",
  "oboe",
  "english_horn",
  "bassoon",
  "clarinet",
  "piccolo",
  "flute",
  "recorder",
  "pan_flute",
  "blown_bottle",
  "shakuhachi",
  "whistle",
  "ocarina",
  "lead_1_square",
  "lead_2_sawtooth",
  "lead_3_calliope",
  "lead_4_chiff",
  "lead_5_charang",
  "lead_6_voice",
  "lead_7_fifths",
  "lead_8_bass_lead",
  "pad_1_new_age",
  "pad_2_warm",
  "pad_3_polysynth",
  "pad_4_choir",
  "pad_5_bowed",
  "pad_6_metallic",
  "pad_7_halo",
  "pad_8_sweep",
  "fx_1_rain",
  "fx_2_soundtrack",
  "fx_3_crystal",
  "fx_4_atmosphere",
  "fx_5_brightness",
  "fx_6_goblins",
  "fx_7_echoes",
  "fx_8_sci_fi",
  "sitar",
  "banjo",
  "shamisen",
  "koto",
  "kalimba",
  "bagpipe",
  "fiddle",
  "shanai",
  "tinkle_bell",
  "agogo",
  "steel_drums",
  "woodblock",
  "taiko_drum",
  "melodic_tom",
  "synth_drum",
  "reverse_cymbal",
  "guitar_fret_noise",
  "breath_noise",
  "seashore",
  "bird_tweet",
  "telephone_ring",
  "helicopter",
  "applause",
  "gunshot"
];
export const GM_ALIASES: Readonly<Record<string, string>> = {
  piano:'acoustic_grand_piano', epiano:'electric_piano_1', rhodes:'electric_piano_1', organ:'drawbar_organ',
  guitar:'acoustic_guitar_nylon', bass:'electric_bass_finger', synth_bass:'synth_bass_1', strings:'string_ensemble_1',
  choir:'choir_aahs', brass:'brass_section', lead:'lead_1_square', pad:'pad_2_warm',
};
export function parseProgram(value: unknown, path = ''): Parsed<number> {
  if (typeof value !== 'string') {
    const hint = typeof value === 'number' && Number.isInteger(value) ? `${value} is "${GM_PROGRAMS[value] ?? 'out of range'}" (0-based) or "${GM_PROGRAMS[value - 1] ?? 'out of range'}" (1-based); use the name.` : 'Use e.g. "acoustic_grand_piano".';
    return { diagnostic: diagnostic('WRONG_TYPE',path,value,'General MIDI program name',hint) };
  }
  const index = GM_PROGRAMS.indexOf(value);
  if (index >= 0) return { value: index };
  const suggestion = Object.hasOwn(GM_ALIASES,value) ? GM_ALIASES[value] : didYouMean(value,GM_PROGRAMS,3);
  return { diagnostic: diagnostic('UNKNOWN_GM_PROGRAM',path,value,'General MIDI program name from Appendix A',suggestion ? `Use "${suggestion}".` : undefined) };
}
